### PR TITLE
Update bitcoin-networks.md

### PR DESCRIPTION
**Pull request by NicolasChoukroun**
Just adding Kryptofranc (KYF) to the list.

### CODE REVIEW

**Comment by guggero** [comment]
I'm pretty sure you will update this code as soon as you figure out that all your addresses will start with an 'X' instead of a 'K'...

See: https://en.bitcoin.it/wiki/List_of_address_prefixes

**Comment by NicolasChoukroun** [comment]
Sure I will. So far the wallet looks like this. Thanks for having spent the time to double check ;) Windows French. Unix English  27.02.2019, 22:13, "Oliver Gugger" <notifications@github.com>:I'm pretty sure you will update this code as soon as you figure out that all your addresses will start with an 'X' instead of a 'K'...See: https://en.bitcoin.it/wiki/List_of_address_prefixes—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by guggero** [comment]
Ok, just wanted to make sure you were aware of this.

**Comment by NicolasChoukroun** [comment]
'k' is a special case... in hex: 6b, in dec=107, it give 'k' for the address.. however, 'K' was wrong and gives q.Thanks for pointing that out. Nikko 27.02.2019, 23:08, "Oliver Gugger" <notifications@github.com>:Ok, just wanted to make sure you were aware of this.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request merged**
